server:
  port: 8000
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeongwon201/fc-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/