server:
  port: 8001
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/gateway-local.p12
    key-store-password: password
    key-alias: localhost
    enabled: true

spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: match
          uri: lb://match
          predicates:
            - Path=/match/**
        - id: marketing
          uri: lb://marketing
          predicates:
            - Path=/marketing/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: query
          uri: lb://query
          predicates:
            - Path=/query/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "busrefresh"
          - "gateway"